import { Client, Storage } from 'node-appwrite';
import fs from 'fs';
import path from 'path';

const envPath = path.resolve(process.cwd(), '.env');
if (fs.existsSync(envPath)) {
  const envConfig = fs.readFileSync(envPath, 'utf8');
  for (const line of envConfig.split('\n')) {
    const [key, val] = line.split('=');
    if (key && val) {
      process.env[key.trim()] = val.trim().replace(/^["']|["']$/g, '');
    }
  }
}

const client = new Client()
  .setEndpoint(process.env.PUBLIC_APPWRITE_ENDPOINT || '')
  .setProject(process.env.PUBLIC_APPWRITE_PROJECT_ID || '')
  .setKey(process.env.APPWRITE_API_KEY || '');

const storage = new Storage(client);

async function run() {
  try {
    const files = await storage.listFiles('products');
    console.log(`Archivos en products: ${files.total}`);
    if (files.total > 0) {
      console.log('Primer archivo:', files.files[0].$id);
      
      // Let's also print the View URL generated by the SDK to see if it matches what I built
      // getFileView returns a URL object or string depending on SDK version
      // Let's see what it prints
      const result = await client.call(
        'get',
        `/storage/buckets/products/files/${files.files[0].$id}/view`,
        {
          'content-type': 'application/json',
        },
        {}
      );
      console.log('API call view test completed.');
    }
  } catch(e: any) {
    console.error('Error listando:', e.message);
  }
}
run();
